### ISSUE TITLE
PHP error kills WP

### ISSUE THREAD

**Issue by cfoellmann** [podlove/podlove-subscribe-button-wp-plugin#36]
if the php version error is triggered there is no going back.
This needs to be changed

**Comment by eteubert** [comment]
Feel free to copy the approach the Publisher plugin uses: https://github.com/podlove/podlove-publisher/blob/master/podlove.php

- move all includes/requires into a `load_...` method
- only invoke this method if version requirement is met
- otherwise, display a notice explaining the issue and disable the plugin
